### ISSUE TITLE
Google published hex

### ISSUE THREAD

**Issue by schurig** [martide/arc_gcs#10]
Hi, I saw that Google now also provides a library: https://hex.pm/packages/google_api_storage

Maybe this lib should rely on the official Google lib?

**Comment by samhamilton** [comment]
@schurig wow that’s exciting if google is putting effort behind elixir. We will defiantly check it out. Thanks l!

**Comment by kolorahl** [comment]
@samhamilton I've created a PR with this change. I had written some of this code on my own when I was going down the rabbit hole of creating my own file upload tool, then I found Arc and this library. Decided I would merge some of my efforts here.

Additionally, there's a v4 signing method which I haven't been able to get working yet but it sounds like the signing method currently being used (v2) may be deprecated once v4 is more established. Maybe you could take a look but my own attempts say that the signature does not match the one they computed, but I'm using the same signing code from your implementation (`base64_url_sign` I think is the function). Just a heads up.

**Comment by samhamilton** [comment]
just merged https://github.com/martide/arc_gcs/pull/76 to master, fixing CI and then will push a release

**Comment by jcelliott** [comment]
Looks like #76 was reverted. Anything I can do to help get that fixed?
