### ISSUE TITLE
Missing changelog entries

### ISSUE THREAD

**Issue by sgerrand** [martide/arc_gcs#105]
The `CHANGELOG.md` file in this package hasn't been updated since v0.2.0. Since then, the package version has moved on to v0.2.3. Is this file still being actively used? If so, will it be backfilled with the changes made since?

I'm asking because there have been some breaking changes from v0.2.1 to v0.2.3 which I've encountered and @dependabot has no changelog to present.

**Comment by samhamilton** [comment]
@sgerrand I have just updated the changelog

**Comment by sgerrand** [comment]
Thanks!
